version: '3.7'
services:
  bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ID=${APP_ID}
      - APP_HASH=${APP_HASH}
      - TOKEN=${TOKEN}
      - VK_TOKEN=${VK_TOKEN}
    volumes:
      - ./session.json:/app/session.json
